name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Node 14'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: '@gvhinks'
      ##################################################
      #   _           _ _     _
      #  | |__  _   _(_) | __| |
      #  | '_ \| | | | | |/ _` |
      #  | |_) | |_| | | | (_| |
      #  |_.__/ \__,_|_|_|\__,_|
      ##################################################
      - name: build
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build

      ###################################################
      ##   _ __  _ __  _ __ ___
      ##  | '_ \| '_ \| '_ ` _ \
      ##  | | | | |_) | | | | | |
      ##  |_| |_| .__/|_| |_| |_|
      ##        |_|
      ###################################################
      - name: npm-publish-dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
  ##################################################
  #    _____           _                                   _     _
  #   |_   _|         | |                                 | |   (_)
  #     | |    _ __   | |_    ___    __ _   _ __    __ _  | |_   _    ___    _ __
  #     | |   | '_ \  | __|  / _ \  / _` | | '__|  / _` | | __| | |  / _ \  | '_ \
  #    _| |_  | | | | | |_  |  __/ | (_| | | |    | (_| | | |_  | | | (_) | | | | |
  #   |_____| |_| |_|  \__|  \___|  \__, | |_|     \__,_|  \__| |_|  \___/  |_| |_|
  #                                  __/ |
  #                                 |___/
  #
  ##################################################
  integration-testing:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: npm init
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm init --yes
          npm install @gvhinks/ls-remote-versions@0.0.0-development
