name: npm-version-7-via-node-15
on: [push, pull_request, workflow_dispatch]
jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node_version: [ 15.x ]
    name: Node ${{ matrix.node_version }} - on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm i --no-package-lock
        if: ${{ startsWith(matrix.node_version, '15') }}
      - run: npm run lint
      - run: npm run test
