name: on-publish-package
on:
  push:
    branches: [ main, 'renovate/**' ]
    pull_request: [ main ]
  workflow_dispatch:
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm-install
        run: npm ci
      - name: linting
        run: npm run lint
      - name: build
        run: npm run build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm-install
        run: npm ci
      - name: linting
        run: npm run lint
      - name: build
        run: npm run build
