name: on-publish-package
on:
  push:
    branches: [ main, 'renovate/**', 'feature/**' ]
    pull_request: [ main ]
  workflow_dispatch:
jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: [14.x]
        name: Node ${{ matrix.node_version }} - on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run lint
      - run: npm tests-only
